source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

inhibit_all_warnings!

target :BRFCore do
	pod 'AFNetworking',				'~> 2.5'
	pod 'BRCocoaLumberjack',		'~> 2.0'
	pod 'BREnvironment',			'~> 1.2'
	pod 'BRLocalize',				:git => 'https://github.com/Blue-Rocket/BRLocalizable.git', :branch => 'master'
	pod 'MAObjCRuntime', 			'~> 0.0.1'
	pod 'Masonry',					'~> 0.6'
	pod 'RestKit/ObjectMapping',	'~> 0.24'
	pod 'SOCKit',             		'~> 1.1'
	pod 'TransformerKit/String',    '~> 0.5'
	
	target :BRFCoreTests do
		pod 'OCHamcrest',			'~> 4.1'
		pod 'OCMock',				'~> 3.1'
		pod 'CocoaHTTPServer',		'~> 2.3'
		pod 'RoutingHTTPServer', 	'~> 1.0'
	end
	
end
